DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS STREAM;
CREATE TABLE STREAM (
  SCode CHAR(3) PRIMARY KEY,
  SName VARCHAR(20),
  HOD   VARCHAR(20)
);
CREATE TABLE STUDENT (
  RollNo INTEGER PRIMARY KEY,
  Name   VARCHAR(20),
  SCode  CHAR(3),
  Marks  INTEGER,
  City   VARCHAR(15),
  Fee    DECIMAL(8,2)
);
INSERT INTO STREAM VALUES ('S01','Computer Science','Sharma');
INSERT INTO STREAM VALUES ('S02','Informatics','Iyer');
INSERT INTO STREAM VALUES ('S03','Physics','Rao');
INSERT INTO STUDENT VALUES (101,'Riya' ,'S01',88  ,'Delhi' ,4500);
INSERT INTO STUDENT VALUES (102,'Aarav','S01',91  ,'Mumbai',4500);
INSERT INTO STUDENT VALUES (103,'Kabir','S02',76  ,'Delhi' ,3800);
INSERT INTO STUDENT VALUES (104,'Meera','S01',94  ,'Pune'  ,4500);
INSERT INTO STUDENT VALUES (105,'Dev'  ,'S02',59  ,'Mumbai',3800);
INSERT INTO STUDENT VALUES (106,'Ishan','S03',67  ,'Delhi' ,4000);
INSERT INTO STUDENT VALUES (107,'Nisha','S02',NULL,'Pune'  ,3800);
